### ISSUE TITLE
Arm64 support? 

### ISSUE THREAD

**Issue by KarateJesus515** [RenderBr/tShock-v5-plugins#4]
Any chance these can be made to work with Arm64? After trying a few of these, they all said they only support x64 architecture.

**Comment by RenderBr** [comment]
> Any chance these can be made to work with Arm64? After trying a few of these, they all said they only support x64 architecture.

You'd have to recompile them all to work for ARM64. Simply open the solutions in visual studio, change the architecture to ARM64 and build it.
