### ISSUE TITLE
UserSpecificFunctions 

### ISSUE THREAD

**Issue by imnagarajan** [RenderBr/tShock-v5-plugins#5]
Can you update UserSpecificFunctions plugin please

**Comment by imnagarajan** [comment]
@RenderBr

**Comment by Evauation** [comment]
He'll work on his own projects or plugins at his own pace. If you want him to update plugins for you, commission him on Ko-Fi: https://ko-fi.com/averageterraria

**Comment by RenderBr** [comment]
Possibly, I have no desire or reason to update this plugin. I may get around to it if I have nothing better to do but if you want it done ASAP, commission me with the link @Evauation posted here.
