### ISSUE TITLE
House region plugin

### ISSUE THREAD

**Issue by ZkilleMito** [RenderBr/tShock-v5-plugins#8]
Update House region
![image](https://github.com/RenderBr/tShock-v5-plugins/assets/38038982/f597c376-2b7a-4302-bc73-4ebbf3d2b016)

**Comment by Maxthegreat99** [comment]
Hello!! Could you please explain when is this error occuring or at least give steps to reproduce it?

**Comment by ZkilleMito** [comment]
when starting the commands to define the terrain, this error occurs

**Comment by Maxthegreat99** [comment]
fixed the issue in https://github.com/RenderBr/tShock-v5-plugins/commit/eb0e3c893b8e69823ea84a68686e77fbc336687c
