### ISSUE TITLE
Source code of Auxiliary Dependency

### ISSUE THREAD

**Issue by dark22** [RenderBr/tShock-v5-plugins#9]
Would it be possible to make the source code of the Auxiliary dependency available again? 
The original link has been removed. 
Thank you for your attention!

**Comment by Maxthegreat99** [comment]
Hello! I think that Average does not intend to publish the source code, as he mentioned in our direct messages:

> ***Auxiliary's source has been made private, but it is required by several plugins, so I decided to include it.***

But, there might be a possibility that he may change his mind in the future, its really up to him.

**Comment by dark22** [comment]
I really appreciate your attention on this, I didn't know about this decision.

**Comment by RenderBr** [comment]
To provide further elaboration, the plugin was not made by me but the owner of TBC. A variety of plugins depend on this library and is still available on NuGet but the author decided to close the source a few months ago unfortunately. If you have any questions on how the library functions I would be happy to answer.
